# echo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://haraldkoch.github.io/helm-charts
      # Chart name
      chart: http-echo
      # Chart version
      targetRevision: 0.3.4
      helm:
        valueFiles:
          # Custom value files from another source
          - $values/apps/http-echo/values-default.yaml
          - $values/apps/http-echo/values-prod.yaml
    - repoURL: https://github.com/sven-dmlr/argo-example.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: http-echo
  syncPolicy:
    automated:
      # enabled: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
